language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install -e .[test]
    - pip install zope.testrunner coverage coveralls
script:
    - coverage run -m zope.testrunner --test-path=src --tests-pattern="^f?tests$"
    - coverage report -m --fail-under=100
after_success:
    - coveralls
notifications:
    email: false
