language: python
sudo: false
matrix:
  include:
    - { python: 2.7, env: TESTS_PATTERN='f?tests' }
    - { python: 3.4, env: TESTS_PATTERN='tests' }
    - { python: 3.5, env: TESTS_PATTERN='tests' }
    - { python: 3.6, env: TESTS_PATTERN='tests' }
install:
    - pip install -e .
    - pip install zope.testrunner coverage coveralls
script:
    - coverage run -m zope.testrunner --test-path=src --tests-pattern="^${TESTS_PATTERN}$" --ignore-new-thread=Dummy
after_success:
    - coveralls
notifications:
    email: false
