language: python
python:
    - 2.6
    - 2.7
install:
    - pip install .
    - pip install zope.testrunner
script:
    - zope-testrunner --test-path=src --tests-pattern='^f?tests$'
notifications:
    email: false
