version: build-{build}-{branch}

environment:
  global:
    # At the moment PyPI has no wheels of ZODB and zope.*.
    PIP_FIND_LINKS: "https://debesis.gedmin.as/wheels/"
  matrix:
    # http://www.appveyor.com/docs/installed-software#python lists available
    # versions
    - PYTHON: "C:\\Python27"

init:
  - "echo %PYTHON%"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - pip install tox

build: off

test_script:
  - tox -e py
